# Generated by Django 4.0.3 on 2022-03-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardalogueapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcollection',
            name='user',
        ),
    ]
