# Generated by Django 4.0.3 on 2022-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardalogueapi', '0002_remove_cardcollection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='cardfrontimages'),
        ),
    ]
